### ISSUE TITLE
Add support for receiving APRS-IS messages

### ISSUE THREAD

**Issue by ampledata** [ampledata/aprs#1]
Currently this module only supports sending APRS-IS frames. It would be nice to receive them as well :).

**Comment by genepool99** [comment]
I would also like to see this, great work still.

**Comment by ampledata** [comment]
@genepool99 I actually added this already :) See: https://github.com/ampledata/aprs#example-2-library-usage---receive

**Comment by ampledata** [comment]
https://github.com/ampledata/aprs#example-2-library-usage---receive
