### ISSUE TITLE
Sends LF+CR instead of CR+LF at line end

### ISSUE THREAD

**Issue by hessu** [ampledata/aprs#17]
Hi,

Minor bug: The APRS-IS line termination is CR+LF (spec: http://aprs-is.net/Connecting.aspx). class TCP(APRS) transmits LF+CR instead:

https://github.com/ampledata/aprs/blob/master/aprs/classes.py#L382

Most APRS-IS servers will currently accept this, but some might not.

The receiving side seems to have this right: https://github.com/ampledata/aprs/blob/master/aprs/classes.py#L407

- Hessu, develops aprsc and aprs.fi

**Comment by ampledata** [comment]
Thank you so much for the fix, I've merged it into the python3_support branch!
